import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>LANDING</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <header>
          <nav className='py-5 bg-gray-900'>
            <div className='container flex flex-wrap items-center  justify-between mx-auto'>
              <a href="" className='flex items-center'>
                <img src="/logo.png" alt="logo" width={36} height={36} className='mr-1' />
                <span className='self-center text-xl font-semibold text-green-200'>
                  Bamboo
                </span>
              </a>
              <div>
                <ul className='flex p-4 mt-4'>
                  <li>
                    <a href="" className=' text-white px-3 font-semibold py-2'>
                      About
                    </a>
                  </li>
                  <li>
                    <a href="" className=' text-white px-3 font-semibold py-2'>
                      Service
                    </a>
                  </li>
                  <li>
                    <a href="" className=' text-white px-3 font-semibold py-2'>
                      Contact Us
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </header>
        <section id='banner' class="bg-[url('/food.jpg')] bg-cover bg-no-repeat">
          <div className='layout flex flex-col justify-center min-h-screen text-center bg-[#00000075]'>
            <h1 className='text-6xl font-bold text-green-300'>
              HelloFood
            </h1>
            <p className='text-xl font-normal text-green-400'>
              FreshFood at Your DoorStep
            </p>
          </div>
        </section>
        <section>
          About
        </section>
        <section>
          Service
        </section>
      </main>
    </>
  )
}
