import Head from 'next/head'
import Hero from '@/components/Hero'
import Reason from '@/components/Reason'
import Variety from '@/components/Variety'
import Front from '@/components/Front'



export default function Home() {
  return (
    <>
    <Front>
        <Head>
          <title>HelloFood</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <Hero/>
          <Reason/>
          <Variety/>
          {/* <Warning/> */}
      </Front>
    </>
  )
}
