import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import Reason from '@/components/Reason'
import Variety from '@/components/Variety'
import Warning from '@/components/Warning'



export default function Home() {
  return (
    <>
    
        <Head>
          <title>HelloFood</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <Navbar/>
          <Hero/>
          <Reason/>
          <Variety/>
          {/* <Warning/> */}
    </>
  )
}
